first_tuple = (1, 2, 3, 4, 5)
print("Вашият начален кортеж е", end=" ")
print(*first_tuple)
my_list = list(first_tuple)
#print(my_list)
my_list.insert(2, 45)
my_list.append(35)
second_tuple = tuple(my_list)
print("Вашият кортеж с добавени елементи е: ", end=" ")
print(*second_tuple)